In [1]:
import json as f

In [6]:
with open(r'C:\Users\Ashu\Desktop\OpenGovDataHack\Working\Education_and_Skilling_v1\Dataset\Classification_of_secondary_schools_by_management_in_Haryana.json','r') as f:
    RawData = f.read()

In [7]:
RawData

'{"fields":[{"id":"a","label":"Year\\/District","type":"string"},{"id":"b","label":"Government","type":"string"},{"id":"c","label":"Non-Govt.","type":"string"},{"id":"d","label":"For Boys","type":"string"},{"id":"e","label":"For Girls","type":"string"},{"id":"f","label":"Total","type":"string"}],"data":[["1966-67","440","157","488","109","597"],["1970-71","797","178","811","164","975"],["1975-76","907","222","931","198","1129"],["1980-81","1226","247","1228","245","1473"],["1985-86","1657","289","1643","303","1946"],["1990-91","1944","412","2001","355","2356"],["1995-96","2345","653","2547","451","2998"],["2000-01","2620","1518","3631","507","4138"],["2005-06","2827","2490","4781","536","5317"],["2010-11","3167","3816","6425","558","6983"],["2011-12","3214","3890","6470","590","7060"],["2012-13 (P)","3159","4179","6819","519","7338"],["Ambala","155","143","288","10","298"],["Panchkula","58","61","116","3","119"],["Yamunanagar","111","215","321","5","326"],["Kurukshetra","112","168","273","7","280"],["Kaithal","144","144","260","28","288"],["Karnal","163","234","379","18","397"],["Panipat","108","168","252","24","276"],["Sonipat","208","247","418","37","455"],["Rohtak","160","226","338","48","386"],["Jhajjar","170","199","337","32","369"],["Faridabad","85","336","404","17","421"],["Palwal","99","188","257","30","287"],["Gurgaon","115","206","306","15","321"],["Mewat","80","71","137","14","151"],["Rewari","146","156","284","18","302"],["Mahendragarh","144","197","328","13","341"],["Bhiwani","304","379","627","56","683"],["Jind","210","224","389","45","434"],["Hisar","267","344","547","64","611"],["Fatehabad","141","124","247","18","265"]]}'

In [81]:
DataObj = json.loads(RawData)

In [82]:
DataObj

{'fields': [{'id': 'a', 'label': 'Year/District', 'type': 'string'},
  {'id': 'b', 'label': 'Government', 'type': 'string'},
  {'id': 'c', 'label': 'Non-Govt.', 'type': 'string'},
  {'id': 'd', 'label': 'For Boys', 'type': 'string'},
  {'id': 'e', 'label': 'For Girls', 'type': 'string'},
  {'id': 'f', 'label': 'Total', 'type': 'string'}],
 'data': [['1966-67', '440', '157', '488', '109', '597'],
  ['1970-71', '797', '178', '811', '164', '975'],
  ['1975-76', '907', '222', '931', '198', '1129'],
  ['1980-81', '1226', '247', '1228', '245', '1473'],
  ['1985-86', '1657', '289', '1643', '303', '1946'],
  ['1990-91', '1944', '412', '2001', '355', '2356'],
  ['1995-96', '2345', '653', '2547', '451', '2998'],
  ['2000-01', '2620', '1518', '3631', '507', '4138'],
  ['2005-06', '2827', '2490', '4781', '536', '5317'],
  ['2010-11', '3167', '3816', '6425', '558', '6983'],
  ['2011-12', '3214', '3890', '6470', '590', '7060'],
  ['2012-13 (P)', '3159', '4179', '6819', '519', '7338'],
  ['Ambala', '155', '143', '288', '10', '298'],
  ['Panchkula', '58', '61', '116', '3', '119'],
  ['Yamunanagar', '111', '215', '321', '5', '326'],
  ['Kurukshetra', '112', '168', '273', '7', '280'],
  ['Kaithal', '144', '144', '260', '28', '288'],
  ['Karnal', '163', '234', '379', '18', '397'],
  ['Panipat', '108', '168', '252', '24', '276'],
  ['Sonipat', '208', '247', '418', '37', '455'],
  ['Rohtak', '160', '226', '338', '48', '386'],
  ['Jhajjar', '170', '199', '337', '32', '369'],
  ['Faridabad', '85', '336', '404', '17', '421'],
  ['Palwal', '99', '188', '257', '30', '287'],
  ['Gurgaon', '115', '206', '306', '15', '321'],
  ['Mewat', '80', '71', '137', '14', '151'],
  ['Rewari', '146', '156', '284', '18', '302'],
  ['Mahendragarh', '144', '197', '328', '13', '341'],
  ['Bhiwani', '304', '379', '627', '56', '683'],
  ['Jind', '210', '224', '389', '45', '434'],
  ['Hisar', '267', '344', '547', '64', '611'],
  ['Fatehabad', '141', '124', '247', '18', '265']]}

In [80]:
DataObj.keys()

dict_keys(['fields', 'data'])

In [73]:
len_Col = len(DataObj['fields'])
Cols = [list(DataObj['fields'][i].values())[1] for i in range(len_Col)]

In [78]:
Cols

['Year/District', 'Government', 'Non-Govt.', 'For Boys', 'For Girls', 'Total']

In [90]:
import pandas as p
Data = p.DataFrame(DataObj['data'],columns = Cols)
Data.head()

  Year/District Government Non-Govt. For Boys For Girls Total
0       1966-67        440       157      488       109   597
1       1970-71        797       178      811       164   975
2       1975-76        907       222      931       198  1129
3       1980-81       1226       247     1228       245  1473
4       1985-86       1657       289     1643       303  1946

In [86]:
type(Data)

pandas.core.frame.DataFrame

In [92]:
list(dir(Data))

['Government',
 'T',
 'Total',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_compare_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_expand_axes',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [103]:
print(Data.shape)
print(Data.size)
print(len(Data))

(32, 6)
192
32

In [112]:
type(Data['Year/District'])

pandas.core.series.Series

In [120]:
DatabyYearMO = Data[:11]

DatabyDistrict = Data[12:]

  Year/District Government Non-Govt. For Boys For Girls Total
0       1966-67        440       157      488       109   597
1       1970-71        797       178      811       164   975
2       1975-76        907       222      931       198  1129
3       1980-81       1226       247     1228       245  1473
4       1985-86       1657       289     1643       303  1946